<footer class="main-footer">
   <!-- Lado derecho del footer -->
   <div class="float-right d-none d-sm-inline">
      <!-- Obtenemos la versión de la aplicación desde el archivo de configuración -->
      Versión <?= htmlspecialchars(config('app.version', '1.0.0'), ENT_QUOTES, 'UTF-8') ?>
   </div>

   <!-- Lado izquierdo del footer -->
   <strong>
      Copyright © 2024-<?= date('Y') ?>
      <a href="https://viex.up.ac.pa" target="_blank">Vicerrectoría de Extensión</a>.
   </strong>
   Universidad de Panamá. Todos los derechos reservados.
</footer>