<footer class="main-footer">
   <div class="container">
      <div class="float-right d-none d-sm-inline">
         Versión <?= htmlspecialchars(config('app.version', '1.0.0'), ENT_QUOTES, 'UTF-8') ?>
      </div>
      <strong>Copyright © 2024-<?= date('Y') ?> <a href="https://viex.up.ac.pa" target="_blank">Vicerrectoría de
            Extensión</a>.</strong> Universidad de Panamá.
   </div>
</footer>