<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>VIEX | Vicerrectoría de Extensión</title>

   <!-- favicon png -->
   <link rel="icon" href="<?= assets('icons/icon_name.png') ?>" type="image/png">

   <!-- Google Font: Source Sans Pro -->
   <link rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
   <!-- Font Awesome Icons -->
   <link rel="stylesheet" href="<?= assets('plugins/fontawesome-free/css/all.min.css') ?>">
   <!-- Theme style -->
   <link rel="stylesheet" href="<?= assets('dist/css/adminlte.min.css') ?>">

   <!-- Estilos personalizados para la Landing Page -->
   <style>
      .hero-section {
         background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://www.up.ac.pa/sites/default/files/inline-images/up-ac-pa-banner-secretaria-general-01.jpg') no-repeat center center;
         background-size: cover;
         color: white;
      }

      .brand-link .brand-image {
         max-height: 33px;
      }

      .feature-icon {
         font-size: 3.5rem;
         color: #007bff;
         margin-bottom: 1rem;
      }
   </style>
</head>