<nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
   <div class="container">
      <a href="<?= route('home.index') ?>" class="navbar-brand">
         <!-- Logo de la Universidad o VIEX -->
         <img src="<?= assets('icons/icon_name.png') ?>" alt="VIEX Logo" class="brand-image">
         <span class="brand-text font-weight-light"><b>VIEX</b></span>
      </a>

      <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse"
         aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse order-3" id="navbarCollapse">
         <ul class="navbar-nav">
            <li class="nav-item">
               <a href="<?= route('home.contact') ?>" class="nav-link">Contacto</a>
            </li>
            <li class="nav-item">
               <a href="<?= route('home.about') ?>" class="nav-link">Acerca de</a>
            </li>
         </ul>
      </div>

      <!-- Botones a la derecha -->
      <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
         <li class="nav-item">
            <a href="<?= route('auth.login.form') ?>" class="btn btn-outline-primary">Iniciar Sesión</a>
         </li>
      </ul>
   </div>
</nav>