<!-- Encabezado de la página -->
<div class="content-header">
   <div class="container">
      <div class="row mb-2">
         <div class="col-sm-6">
            <h1 class="m-0"> Acerca de la Plataforma VIEX</h1>
         </div>
      </div>
   </div>
</div>

<!-- Contenido principal -->
<div class="content">
   <div class="container">
      <div class="card card-solid">
         <div class="card-body">
            <div class="row">
               <div class="col-12 col-sm-6">
                  <h3 class="d-inline-block d-sm-none">Misión y Visión</h3>
                  <div class="col-12">
                     <img
                        src="https://www.up.ac.pa/sites/default/files/inline-images/up-ac-pa-somos-todos-somos-up-facultad-de-informatica-electronica-y-comunicacion-01.jpg"
                        class="product-image" alt="Imagen Universidad">
                  </div>
               </div>
               <div class="col-12 col-sm-6">
                  <h3 class="my-3">Nuestra Misión</h3>
                  <p class="lead">Proveer una herramienta tecnológica, centralizada y eficiente que digitalice y
                     transparente el ciclo de vida completo de los trabajos de extensión de la Universidad de Panamá,
                     desde su registro inicial hasta su certificación final.</p>
                  <hr>
                  <h4>¿Para Quién es VIEX?</h4>
                  <ul class="list-unstyled">
                     <li><i class="fas fa-user-tie text-primary"></i> <strong>Profesores y Proponentes:</strong> Para un
                        registro ágil y un seguimiento claro de sus iniciativas.</li>
                     <li><i class="fas fa-sitemap text-primary"></i> <strong>Coordinadores y Directivos:</strong> Para
                        una gestión y validación estandarizada y eficiente.</li>
                     <li><i class="fas fa-university text-primary"></i> <strong>Vicerrectoría de Extensión:</strong>
                        Para una visión global, generación de estadísticas y certificación ágil del impacto de la
                        extensión universitaria.</li>
                  </ul>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>