<div class="container mt-5">
   <h1>Acerca de Nosotros</h1>
   <hr>
   <p class="lead">La plataforma VIEX es una iniciativa de la Vicerrectoría de Extensión para modernizar y transparentar la gestión de los trabajos de extensión en la Universidad de Panamá.</p>
   <p>Nuestro objetivo es proporcionar una herramienta eficiente y centralizada para que profesores, coordinadores y directivos puedan registrar, evaluar y certificar las valiosas labores de extensión que conectan a nuestra universidad con la comunidad.</p>
</div>