<div class="container mt-5">
   <h1>Contacto</h1>
   <hr>
   <p class="lead">Para soporte técnico o consultas sobre el uso de la plataforma, puede contactarnos a través de los siguientes medios:</p>
   <ul>
      <li><strong>Correo Electrónico:</strong> soporte.viex@up.ac.pa</li>
      <li><strong>Teléfono:</strong> (507) 523-XXXX</li>
      <li><strong>Oficina:</strong> Vicerrectoría de Extensión, Edificio A, Campus Central.</li>
   </ul>
</div>