<div class="container mt-5">
   <div class="p-5 mb-4 bg-light rounded-3">
      <div class="container-fluid py-5">
         <h1 class="display-5 fw-bold">Bienvenido a VIEX</h1>
         <p class="col-md-8 fs-4">La Plataforma de Registro y Certificación de Trabajos de Extensión de la Universidad de Panamá.</p>
         <hr class="my-4">
         <p>Desde aquí puede iniciar sesión para gestionar sus trabajos o consultar información pública sobre las iniciativas de extensión.</p>
         <a class="btn btn-primary btn-lg" href="<?= route('auth.login.form') ?>" role="button">Iniciar Sesión</a>
      </div>
   </div>
</div>