<h1 class="display-5 fw-bold">Workflow Module</h1>
<p class="fs-5 col-md-8">
   Bienvenido a Phast Framework :: Aplicación de ejemplo. Esta es una plantilla base para comenzar rápidamente con tu desarrollo.
   Puedes personalizar este contenido y añadir tus elementos específicos aquí.
</p>

<div class="p-5 mb-4 bg-light rounded-3">
   <div class="container-fluid py-5">
         <h2 class="display-6 fw-bold">Sección: workflow/index.view.phtml</h2>
         <p class="col-md-8 fs-5">
            Este bloque representa el contenido principal para la acción o vista actual.
            Aquí es donde colocarás los elementos específicos de tu página.
         </p>
   </div>
</div>
